project_id = "nypedthwyhisgzjsiabw"

[functions.manage-subscription]
verify_jwt = false

[functions.subscription-webhook]
verify_jwt = false

[functions.public-booking]
verify_jwt = false

[functions.generate-website-copy]
verify_jwt = false

[functions.auto-generate-recurring-jobs]
verify_jwt = false

[functions.stripe-payment-link-webhook]
verify_jwt = false
